language: dart
services:
  - rabbitmq
jobs:
  include:
    - stage: run tests
      dart: stable
      script:
        - export PATH=$PATH:"~/.pub-cache/bin"
        - pub get
        - pub global activate coverage
        - dartfmt -n --set-exit-if-changed .
        - dartanalyzer --fatal-warnings --fatal-hints --fatal-lints ./
        - cd test
        - bash run.sh
      after_success:
        - bash test_coverage.sh
        - dart upload_coverage.dart
