include: package:pedantic/analysis_options.yaml
linter:
  rules:
    - avoid_null_checks_in_equality_operators
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_null_aware_operators
    - prefer_void_to_null
