name: dart_amqp
description: >
  Dart AMQP client implementing protocol version 0.9.1
version: 0.0.3
author: Achilleas Anagnostopoulos
homepage: https://github.com/achilleasa/dart_amqp
dependencies:
  logging: ">=0.9.3 <0.10.0"
dev_dependencies:
  unittest: any
  mock: ">=0.11.0+2 <0.12.0"
  http: ">=0.11.1+1 <0.12.0"
  xml: ">=2.2.3 <3.0.0"
